// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCompany = `-- name: ArchiveCompany :exec
UPDATE companies
SET archived_at = now()
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveCompany(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveCompany, id)
	return err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, slug, zitadel_org_id)
VALUES ($1, $2, $3)
RETURNING
    id,
    name,
    slug,
    zitadel_org_id,
    created_at,
    archived_at
`

type CreateCompanyParams struct {
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	ZitadelOrgID string `json:"zitadel_org_id"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany, arg.Name, arg.Slug, arg.ZitadelOrgID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ZitadelOrgID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT
    id,
    name,
    slug,
    zitadel_org_id,
    created_at,
    archived_at
FROM companies
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetCompany(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ZitadelOrgID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT
    id,
    name,
    slug,
    zitadel_org_id,
    created_at,
    archived_at
FROM companies
WHERE archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ZitadelOrgID,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
