// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contactExistsByCompanyEmail = `-- name: ContactExistsByCompanyEmail :one
SELECT EXISTS(
    SELECT 1 FROM contacts
    WHERE company_id = $1
      AND email IS NOT NULL
      AND lower(email) = lower($2)
      AND archived_at IS NULL
) AS found
`

type ContactExistsByCompanyEmailParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Lower     string      `json:"lower"`
}

// Used by InviteMember to fail fast on a duplicate email before
// creating the ZITADEL user. Matches the case-insensitive uniqueness
// predicate enforced by the contacts_company_email_active_unique
// partial index so the app-level pre-check stays consistent with the
// DB-level guarantee.
func (q *Queries) ContactExistsByCompanyEmail(ctx context.Context, arg ContactExistsByCompanyEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactExistsByCompanyEmail, arg.CompanyID, arg.Lower)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    company_id,
    full_name,
    job_title,
    email,
    phone,
    mobile,
    notes,
    zitadel_user_id,
    identity_source,
    external_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, full_name, job_title, email, phone, mobile, notes, zitadel_user_id, identity_source, external_id, created_at, archived_at
`

type CreateContactParams struct {
	CompanyID      pgtype.UUID `json:"company_id"`
	FullName       string      `json:"full_name"`
	JobTitle       pgtype.Text `json:"job_title"`
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	Mobile         pgtype.Text `json:"mobile"`
	Notes          pgtype.Text `json:"notes"`
	ZitadelUserID  pgtype.Text `json:"zitadel_user_id"`
	IdentitySource string      `json:"identity_source"`
	ExternalID     pgtype.Text `json:"external_id"`
}

// Inserts a contact in the given company. Identity columns
// (zitadel_user_id, identity_source, external_id) are accepted as
// explicit parameters so the install orchestrator + invite flow can
// supply them; the contacts handler defaults identity_source to
// 'manual' app-side when omitted.
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.CompanyID,
		arg.FullName,
		arg.JobTitle,
		arg.Email,
		arg.Phone,
		arg.Mobile,
		arg.Notes,
		arg.ZitadelUserID,
		arg.IdentitySource,
		arg.ExternalID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FullName,
		&i.JobTitle,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.Notes,
		&i.ZitadelUserID,
		&i.IdentitySource,
		&i.ExternalID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, company_id, full_name, job_title, email, phone, mobile, notes, zitadel_user_id, identity_source, external_id, created_at, archived_at
FROM contacts
WHERE id = $1 AND archived_at IS NULL
`

// Returns the active contact by id. Used by handlers that accept a
// contact_id from the wire (TeamService change-role/suspend/archive,
// ContactsService single-record operations).
func (q *Queries) GetContact(ctx context.Context, id pgtype.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FullName,
		&i.JobTitle,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.Notes,
		&i.ZitadelUserID,
		&i.IdentitySource,
		&i.ExternalID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
