// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    company_id,
    full_name,
    job_title,
    email,
    phone,
    mobile,
    notes,
    zitadel_user_id,
    identity_source,
    external_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, full_name, job_title, email, phone, mobile, notes, zitadel_user_id, identity_source, external_id, created_at, archived_at
`

type CreateContactParams struct {
	CompanyID      pgtype.UUID `json:"company_id"`
	FullName       string      `json:"full_name"`
	JobTitle       pgtype.Text `json:"job_title"`
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	Mobile         pgtype.Text `json:"mobile"`
	Notes          pgtype.Text `json:"notes"`
	ZitadelUserID  pgtype.Text `json:"zitadel_user_id"`
	IdentitySource string      `json:"identity_source"`
	ExternalID     pgtype.Text `json:"external_id"`
}

// Inserts a contact in the given company. Identity columns
// (zitadel_user_id, identity_source, external_id) are accepted as
// explicit parameters so the install orchestrator + invite flow can
// supply them; the contacts handler defaults identity_source to
// 'manual' app-side when omitted.
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.CompanyID,
		arg.FullName,
		arg.JobTitle,
		arg.Email,
		arg.Phone,
		arg.Mobile,
		arg.Notes,
		arg.ZitadelUserID,
		arg.IdentitySource,
		arg.ExternalID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FullName,
		&i.JobTitle,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.Notes,
		&i.ZitadelUserID,
		&i.IdentitySource,
		&i.ExternalID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
