// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type WorkspaceInstallState string

const (
	WorkspaceInstallStateNotInitialized WorkspaceInstallState = "not_initialized"
	WorkspaceInstallStateProvisioning   WorkspaceInstallState = "provisioning"
	WorkspaceInstallStateReady          WorkspaceInstallState = "ready"
	WorkspaceInstallStateFailed         WorkspaceInstallState = "failed"
)

func (e *WorkspaceInstallState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceInstallState(s)
	case string:
		*e = WorkspaceInstallState(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceInstallState: %T", src)
	}
	return nil
}

type NullWorkspaceInstallState struct {
	WorkspaceInstallState WorkspaceInstallState `json:"workspace_install_state"`
	Valid                 bool                  `json:"valid"` // Valid is true if WorkspaceInstallState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceInstallState) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceInstallState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceInstallState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceInstallState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceInstallState), nil
}

type Company struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	ZitadelOrgID string             `json:"zitadel_org_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
}

type Workspace struct {
	ID                 int16                 `json:"id"`
	Name               string                `json:"name"`
	Slug               string                `json:"slug"`
	Timezone           string                `json:"timezone"`
	CurrencyCode       string                `json:"currency_code"`
	InstallState       WorkspaceInstallState `json:"install_state"`
	InstallError       pgtype.Text           `json:"install_error"`
	ZitadelOrgID       pgtype.Text           `json:"zitadel_org_id"`
	ZitadelProjectID   pgtype.Text           `json:"zitadel_project_id"`
	ZitadelSpaAppID    pgtype.Text           `json:"zitadel_spa_app_id"`
	ZitadelSpaClientID pgtype.Text           `json:"zitadel_spa_client_id"`
	CreatedAt          pgtype.Timestamptz    `json:"created_at"`
	InitializedAt      pgtype.Timestamptz    `json:"initialized_at"`
}
