// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveCompany(ctx context.Context, id pgtype.UUID) error
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	GetCompany(ctx context.Context, id pgtype.UUID) (Company, error)
	GetWorkspace(ctx context.Context) (Workspace, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	MarkWorkspaceFailed(ctx context.Context, installError pgtype.Text) error
	MarkWorkspaceProvisioning(ctx context.Context, arg MarkWorkspaceProvisioningParams) error
	MarkWorkspaceReady(ctx context.Context) error
	PersistZitadelIDs(ctx context.Context, arg PersistZitadelIDsParams) error
}

var _ Querier = (*Queries)(nil)
