// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspace = `-- name: GetWorkspace :one
SELECT
    id,
    name,
    slug,
    timezone,
    currency_code,
    install_state,
    install_error,
    zitadel_org_id,
    zitadel_project_id,
    zitadel_spa_app_id,
    zitadel_spa_client_id,
    created_at,
    initialized_at
FROM workspace
WHERE id = 1
`

func (q *Queries) GetWorkspace(ctx context.Context) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.CurrencyCode,
		&i.InstallState,
		&i.InstallError,
		&i.ZitadelOrgID,
		&i.ZitadelProjectID,
		&i.ZitadelSpaAppID,
		&i.ZitadelSpaClientID,
		&i.CreatedAt,
		&i.InitializedAt,
	)
	return i, err
}

const markWorkspaceFailed = `-- name: MarkWorkspaceFailed :exec
UPDATE workspace
SET
    install_state = 'failed',
    install_error = $1
WHERE id = 1
`

func (q *Queries) MarkWorkspaceFailed(ctx context.Context, installError pgtype.Text) error {
	_, err := q.db.Exec(ctx, markWorkspaceFailed, installError)
	return err
}

const markWorkspaceProvisioning = `-- name: MarkWorkspaceProvisioning :exec
UPDATE workspace
SET
    name          = $1,
    slug          = $2,
    timezone      = $3,
    currency_code = $4,
    install_state = 'provisioning',
    install_error = NULL
WHERE id = 1
`

type MarkWorkspaceProvisioningParams struct {
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	Timezone     string `json:"timezone"`
	CurrencyCode string `json:"currency_code"`
}

func (q *Queries) MarkWorkspaceProvisioning(ctx context.Context, arg MarkWorkspaceProvisioningParams) error {
	_, err := q.db.Exec(ctx, markWorkspaceProvisioning,
		arg.Name,
		arg.Slug,
		arg.Timezone,
		arg.CurrencyCode,
	)
	return err
}

const markWorkspaceReady = `-- name: MarkWorkspaceReady :exec
UPDATE workspace
SET
    install_state  = 'ready',
    install_error  = NULL,
    initialized_at = now()
WHERE id = 1
`

func (q *Queries) MarkWorkspaceReady(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markWorkspaceReady)
	return err
}

const persistZitadelIDs = `-- name: PersistZitadelIDs :exec
UPDATE workspace
SET
    zitadel_org_id        = $1,
    zitadel_project_id    = $2,
    zitadel_spa_app_id    = $3,
    zitadel_spa_client_id = $4
WHERE id = 1
`

type PersistZitadelIDsParams struct {
	ZitadelOrgID       pgtype.Text `json:"zitadel_org_id"`
	ZitadelProjectID   pgtype.Text `json:"zitadel_project_id"`
	ZitadelSpaAppID    pgtype.Text `json:"zitadel_spa_app_id"`
	ZitadelSpaClientID pgtype.Text `json:"zitadel_spa_client_id"`
}

func (q *Queries) PersistZitadelIDs(ctx context.Context, arg PersistZitadelIDsParams) error {
	_, err := q.db.Exec(ctx, persistZitadelIDs,
		arg.ZitadelOrgID,
		arg.ZitadelProjectID,
		arg.ZitadelSpaAppID,
		arg.ZitadelSpaClientID,
	)
	return err
}
