// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_grants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePendingGrant = `-- name: ActivatePendingGrant :exec
UPDATE workspace_grants
SET status = 'active'
WHERE contact_id = $1
  AND status = 'not_signed_in_yet'
`

// Idempotent first-sign-in transition. Only flips when the grant is
// currently 'not_signed_in_yet', so concurrent activations cannot
// accidentally clobber a later 'suspended' state. Called by the authz
// middleware on every authenticated request whose grant is pending —
// the WHERE clause makes it a no-op for already-active rows.
func (q *Queries) ActivatePendingGrant(ctx context.Context, contactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activatePendingGrant, contactID)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*)::BIGINT AS count
FROM workspace_grants
WHERE role = 'admin'
  AND status = 'active'
`

// Used by the last-admin invariant to short-circuit demote/suspend/
// archive operations that would leave zero active admins. The partial
// index workspace_grants_active_admins from 00007 makes this a
// micro-cheap lookup.
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspaceGrant = `-- name: CreateWorkspaceGrant :one
INSERT INTO workspace_grants (
    contact_id,
    role,
    status,
    granted_by_contact_id
)
VALUES ($1, $2, $3, $4)
RETURNING contact_id, role, status, last_seen_at, granted_at, granted_by_contact_id
`

type CreateWorkspaceGrantParams struct {
	ContactID          pgtype.UUID   `json:"contact_id"`
	Role               WorkspaceRole `json:"role"`
	Status             GrantStatus   `json:"status"`
	GrantedByContactID pgtype.UUID   `json:"granted_by_contact_id"`
}

// Inserts the grant for a contact. Status defaults to 'active' for the
// install-time admin grant; the team invite flow will pass
// 'not_signed_in_yet' for new members.
func (q *Queries) CreateWorkspaceGrant(ctx context.Context, arg CreateWorkspaceGrantParams) (WorkspaceGrant, error) {
	row := q.db.QueryRow(ctx, createWorkspaceGrant,
		arg.ContactID,
		arg.Role,
		arg.Status,
		arg.GrantedByContactID,
	)
	var i WorkspaceGrant
	err := row.Scan(
		&i.ContactID,
		&i.Role,
		&i.Status,
		&i.LastSeenAt,
		&i.GrantedAt,
		&i.GrantedByContactID,
	)
	return i, err
}

const getGrantByContactID = `-- name: GetGrantByContactID :one
SELECT contact_id, role, status, last_seen_at, granted_at, granted_by_contact_id
FROM workspace_grants
WHERE contact_id = $1
`

func (q *Queries) GetGrantByContactID(ctx context.Context, contactID pgtype.UUID) (WorkspaceGrant, error) {
	row := q.db.QueryRow(ctx, getGrantByContactID, contactID)
	var i WorkspaceGrant
	err := row.Scan(
		&i.ContactID,
		&i.Role,
		&i.Status,
		&i.LastSeenAt,
		&i.GrantedAt,
		&i.GrantedByContactID,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT
    c.id           AS contact_id,
    c.full_name    AS full_name,
    c.email        AS email,
    g.role         AS role,
    g.status       AS status,
    g.last_seen_at AS last_seen_at,
    c.created_at   AS created_at
FROM workspace_grants g
INNER JOIN contacts c ON c.id = g.contact_id
INNER JOIN companies co ON co.id = c.company_id
WHERE co.is_workspace_owner = TRUE
  AND c.archived_at IS NULL
ORDER BY c.created_at ASC
`

type ListTeamMembersRow struct {
	ContactID  pgtype.UUID        `json:"contact_id"`
	FullName   string             `json:"full_name"`
	Email      pgtype.Text        `json:"email"`
	Role       WorkspaceRole      `json:"role"`
	Status     GrantStatus        `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Returns every non-archived team member (contact + grant at the MSP
// company). Ordered by creation ascending so the initial install
// admin appears first and the list is stable across calls.
func (q *Queries) ListTeamMembers(ctx context.Context) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ContactID,
			&i.FullName,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTeamCallerByZitadelUserID = `-- name: ResolveTeamCallerByZitadelUserID :one
SELECT
    c.id            AS contact_id,
    c.archived_at   AS contact_archived_at,
    g.role          AS grant_role,
    g.status        AS grant_status,
    g.last_seen_at  AS grant_last_seen_at
FROM contacts AS c
LEFT JOIN workspace_grants AS g ON g.contact_id = c.id
WHERE c.zitadel_user_id = $1
LIMIT 1
`

type ResolveTeamCallerByZitadelUserIDRow struct {
	ContactID         pgtype.UUID        `json:"contact_id"`
	ContactArchivedAt pgtype.Timestamptz `json:"contact_archived_at"`
	GrantRole         NullWorkspaceRole  `json:"grant_role"`
	GrantStatus       NullGrantStatus    `json:"grant_status"`
	GrantLastSeenAt   pgtype.Timestamptz `json:"grant_last_seen_at"`
}

// Single-query authz resolution used by internal/authz/middleware.
// Joins contacts to its (optional) workspace_grants row, returning
// everything the middleware needs in one round-trip:
//   - contact_id      — request context
//   - role            — policy enforcement
//   - grant_status    — suspended / not_signed_in_yet / active branches
//   - last_seen_at    — throttled update decision
//
// LEFT JOIN keeps a contact-without-grant valid; the middleware then
// decides 401 vs 403 based on whether the grant exists.
func (q *Queries) ResolveTeamCallerByZitadelUserID(ctx context.Context, zitadelUserID pgtype.Text) (ResolveTeamCallerByZitadelUserIDRow, error) {
	row := q.db.QueryRow(ctx, resolveTeamCallerByZitadelUserID, zitadelUserID)
	var i ResolveTeamCallerByZitadelUserIDRow
	err := row.Scan(
		&i.ContactID,
		&i.ContactArchivedAt,
		&i.GrantRole,
		&i.GrantStatus,
		&i.GrantLastSeenAt,
	)
	return i, err
}

const touchLastSeen = `-- name: TouchLastSeen :exec
UPDATE workspace_grants
SET last_seen_at = now()
WHERE contact_id = $1
`

// Throttled in-memory by the middleware; this query is fired only when
// the in-memory check decides the persisted value is stale. Setting
// last_seen_at = now() unconditionally is intentional: the throttle
// already absorbed the high-frequency case.
func (q *Queries) TouchLastSeen(ctx context.Context, contactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchLastSeen, contactID)
	return err
}

const updateGrantRole = `-- name: UpdateGrantRole :exec
UPDATE workspace_grants
SET role = $2
WHERE contact_id = $1
`

type UpdateGrantRoleParams struct {
	ContactID pgtype.UUID   `json:"contact_id"`
	Role      WorkspaceRole `json:"role"`
}

func (q *Queries) UpdateGrantRole(ctx context.Context, arg UpdateGrantRoleParams) error {
	_, err := q.db.Exec(ctx, updateGrantRole, arg.ContactID, arg.Role)
	return err
}

const updateGrantStatus = `-- name: UpdateGrantStatus :exec
UPDATE workspace_grants
SET status = $2
WHERE contact_id = $1
`

type UpdateGrantStatusParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Status    GrantStatus `json:"status"`
}

func (q *Queries) UpdateGrantStatus(ctx context.Context, arg UpdateGrantStatusParams) error {
	_, err := q.db.Exec(ctx, updateGrantStatus, arg.ContactID, arg.Status)
	return err
}
