// Code generated by gofra generate config; DO NOT EDIT.
package config

// ZitadelConfig — ZitadelConfig holds connection settings for the ZITADEL admin client Gospa.
type ZitadelConfig struct {
	// Base URL of the ZITADEL instance for the Management and v2 APIs.
	AdminAPIURL string `koanf:"admin_api_url" yaml:"admin_api_url"`
	// Path to the file holding the provisioner Personal Access Token.
	ProvisionerPatFile string `koanf:"provisioner_pat_file" yaml:"provisioner_pat_file"`
}

// AuthConfig — AuthConfig holds server-side authentication settings for JWT validation.
type AuthConfig struct {
	// ZITADEL issuer URL used for OIDC discovery and JWKS fetching.
	Issuer string `koanf:"issuer" yaml:"issuer"`
	// Expected audience claim in JWT access tokens (typically the ZITADEL.
	Audience string `koanf:"audience" yaml:"audience"`
}

// DatabaseConfig — DatabaseConfig holds PostgreSQL connection and pool settings.
type DatabaseConfig struct {
	// PostgreSQL connection string in URL or keyword/value format.
	DSN string `koanf:"dsn" yaml:"dsn"`
	// Maximum number of connections in the pool (0 = pgxpool default).
	MaxConns int32 `koanf:"max_conns" yaml:"max_conns"`
	// Minimum number of idle connections maintained (0 = pgxpool default).
	MinConns int32 `koanf:"min_conns" yaml:"min_conns"`
	// Maximum time a connection can be reused, as a Go duration string such as 1h. Empty uses pgxpool default.
	MaxConnLifetime string `koanf:"max_conn_lifetime" yaml:"max_conn_lifetime"`
	// Maximum time a connection can sit idle, as a Go duration string such as 30m. Empty uses pgxpool default.
	MaxConnIdleTime string `koanf:"max_conn_idle_time" yaml:"max_conn_idle_time"`
	// Interval between pool health checks, as a Go duration string such as 1m. Empty uses pgxpool default.
	HealthCheckPeriod string `koanf:"health_check_period" yaml:"health_check_period"`
	// Run goose migrations on startup. Safe for dev; use a separate migration step in production.
	AutoMigrate bool `koanf:"auto_migrate" yaml:"auto_migrate"`
}

// PublicAuthConfig — PublicAuthConfig holds browser-safe OIDC authentication settings.
type PublicAuthConfig struct {
	// OIDC issuer URL (ZITADEL runs on :8081 in the default docker-compose setup).
	Issuer string `koanf:"issuer" yaml:"issuer" json:"issuer"`
	// OIDC browser client ID.
	ClientID string `koanf:"client_id" yaml:"client_id" json:"clientId"`
	// OIDC scopes requested during login.
	Scopes []string `koanf:"scopes" yaml:"scopes" json:"scopes"`
	// Auth callback path.
	RedirectPath string `koanf:"redirect_path" yaml:"redirect_path" json:"redirectPath"`
	// Redirect path after logout.
	PostLogoutRedirectPath string `koanf:"post_logout_redirect_path" yaml:"post_logout_redirect_path" json:"postLogoutRedirectPath"`
	// ZITADEL organization ID the SPA scopes its login request to via the.
	OrgID string `koanf:"org_id" yaml:"org_id" json:"orgId"`
}

// PublicConfig — PublicConfig holds browser-safe configuration delivered to the frontend.
type PublicConfig struct {
	// Display name shown in the browser.
	AppName string `koanf:"app_name" yaml:"app_name" json:"appName"`
	// Base URL for API calls from the frontend.
	APIBaseURL string `koanf:"api_base_url" yaml:"api_base_url" json:"apiBaseUrl"`
	// Authentication configuration.
	Auth PublicAuthConfig `koanf:"auth" yaml:"auth" json:"auth"`
}

// AppConfig — AppConfig holds server-side application settings.
type AppConfig struct {
	// Application name, used in logs and runtime display.
	Name string `koanf:"name" yaml:"name"`
	// HTTP server port.
	Port int32 `koanf:"port" yaml:"port"`
}

// Config — Config is the root configuration for the application.
type Config struct {
	// Server configuration.
	App AppConfig `koanf:"app" yaml:"app"`
	// Public browser-safe configuration served at /_gofra/config.js.
	Public PublicConfig `koanf:"public" yaml:"public"`
	// Database configuration.
	Database DatabaseConfig `koanf:"database" yaml:"database"`
	// Authentication configuration for JWT validation.
	Auth AuthConfig `koanf:"auth" yaml:"auth"`
	// ZITADEL provisioning configuration (bootstrap + admin API client).
	Zitadel ZitadelConfig `koanf:"zitadel" yaml:"zitadel"`
}

// DefaultConfig returns a Config with all proto-annotated defaults applied.
func DefaultConfig() *Config {
	return &Config{
		App: AppConfig{
			Name: "gospa",
			Port: 3000,
		},
		Public: PublicConfig{
			AppName:    "gospa",
			APIBaseURL: "http://localhost:3000",
			Auth: PublicAuthConfig{
				Issuer:                 "http://localhost:8081",
				ClientID:               "gospa-web",
				Scopes:                 []string{"openid", "profile", "email"},
				RedirectPath:           "/auth/callback",
				PostLogoutRedirectPath: "/",
			},
		},
		Database: DatabaseConfig{
			DSN: "postgres://postgres:postgres@localhost:5432/gospa?sslmode=disable",
		},
		Auth: AuthConfig{},
		Zitadel: ZitadelConfig{
			AdminAPIURL:        "http://localhost:8081",
			ProvisionerPatFile: ".secrets/zitadel-provisioner.pat",
		},
	}
}
