// Code generated by gofra generate config; DO NOT EDIT.
package config

import (
	runtimeconfig "github.com/Gabrielbdd/gofra/runtime/config"

	flag "github.com/spf13/pflag"
)

// NewFlagSet returns a pflag.FlagSet with CLI flags for all non-secret config
// fields. Flags use dotted key paths matching the YAML structure
// (e.g., --app.port, --public.app_name).
func NewFlagSet() *flag.FlagSet {
	f := flag.NewFlagSet("gofra", flag.ContinueOnError)
	f.String("app.name", "", "Application name, used in logs and runtime display")
	f.Int32("app.port", 0, "HTTP server port")
	f.String("public.app_name", "", "Display name shown in the browser")
	f.String("public.api_base_url", "", "Base URL for API calls from the frontend")
	f.String("public.auth.issuer", "", "OIDC issuer URL (ZITADEL runs on :8081 in the default docker-compose setup)")
	f.String("public.auth.client_id", "", "OIDC browser client ID")
	f.String("public.auth.redirect_path", "", "Auth callback path")
	f.String("public.auth.post_logout_redirect_path", "", "Redirect path after logout")
	f.Int32("database.max_conns", 0, "Maximum number of connections in the pool (0 = pgxpool default)")
	f.Int32("database.min_conns", 0, "Minimum number of idle connections maintained (0 = pgxpool default)")
	f.String("database.max_conn_lifetime", "", "Maximum time a connection can be reused, as a Go duration string such as 1h. Empty uses pgxpool default")
	f.String("database.max_conn_idle_time", "", "Maximum time a connection can sit idle, as a Go duration string such as 30m. Empty uses pgxpool default")
	f.String("database.health_check_period", "", "Interval between pool health checks, as a Go duration string such as 1m. Empty uses pgxpool default")
	f.Bool("database.auto_migrate", false, "Run goose migrations on startup. Safe for dev; use a separate migration step in production")
	f.String("auth.issuer", "", "ZITADEL issuer URL used for OIDC discovery and JWKS fetching")
	f.String("auth.audience", "", "Expected audience claim in JWT access tokens (typically the ZITADEL")
	return f
}

// Load reads config using four-layer precedence: struct defaults, YAML file,
// environment variables, and CLI flags.
func Load(args []string, opts ...runtimeconfig.LoadOption) (*Config, error) {
	defaults := []runtimeconfig.LoadOption{runtimeconfig.WithFlags(NewFlagSet())}
	return runtimeconfig.Load(*DefaultConfig(), args, append(defaults, opts...)...)
}
