// Code generated by gofra generate config; DO NOT EDIT.
package config

import (
	"fmt"
	"net/http"

	runtimeconfig "github.com/Gabrielbdd/gofra/runtime/config"
)

// BindPublicConfig returns a copy of the public config subtree. A fresh copy
// is returned on each call so mutators cannot modify the shared application
// config.
func BindPublicConfig(cfg *Config) (*PublicConfig, error) {
	if cfg == nil {
		return nil, fmt.Errorf("config: nil *Config")
	}
	copy := cfg.Public
	return &copy, nil
}

// PublicConfigHandler returns an HTTP handler that serves the public config
// as JavaScript at /_gofra/config.js.
func PublicConfigHandler(
	cfg *Config,
	opts ...runtimeconfig.Option[PublicConfig],
) http.Handler {
	return runtimeconfig.Handler(
		runtimeconfig.NewResolver(cfg, BindPublicConfig, opts...),
	)
}
